<?php

declare(strict_types=1);

namespace Infocyph\PHPForge\Support;

/**
 * Publishes deterministic companion resources for a PHPForge knowledge base.
 *
 * @phpstan-import-type FileRecord from KnowledgeFileCatalog
 * @phpstan-import-type KnowledgeDocument from KnowledgeBase
 * @phpstan-import-type GraphNodeSummary from KnowledgeGraphAnalyzer
 * @phpstan-import-type GraphCommunity from KnowledgeGraphAnalyzer
 * @phpstan-import-type GraphBridge from KnowledgeGraphAnalyzer
 * @phpstan-import-type GraphHealth from KnowledgeGraphAnalyzer
 * @phpstan-type KnowledgeAnalysis array{schema:string,schema_version:int,fingerprint:string,node_count:int,edge_count:int,file_count:int,node_types:array<string,int>,relationships:array<string,int>,languages:array<string,int>,central_nodes:list<array{id:string,type:string,name:string,file:string,degree:int}>,node_communities:array<string,int>,communities:list<GraphCommunity>,god_nodes:list<GraphNodeSummary>,surprising_connections:list<GraphBridge>,suggested_questions:list<array{type:string,question:string,why:string}>,graph_health:GraphHealth,certainties:array<string,int>,resolutions:array<string,int>}
 */
final class KnowledgeArtifacts
{
    private const string HTML_MARKER = '<meta name="generator" content="PHPForge knowledgebase">';

    private const string REPORT_MARKER = '<!-- Generated by PHPForge knowledgebase. -->';

    public function assertWritable(string $knowledgePath): void
    {
        $this->assertWritableTargets($this->paths($knowledgePath));
    }

    /**
     * @param array<string, mixed> $document
     * @param list<FileRecord> $records
     * @return list<string>
     */
    public function publish(array $document, array $records, string $knowledgePath): array
    {
        /** @var KnowledgeDocument $document */
        $paths = $this->paths($knowledgePath);
        $this->assertWritableTargets($paths);
        $analysis = $this->analysis($document, $records);
        $manifest = $this->manifest($document, $records);
        $this->writeJson($paths['manifest'], $manifest);
        $this->writeJson($paths['analysis'], $analysis);
        $this->write($paths['report'], $this->report($document, $analysis));
        $this->write($paths['html'], $this->html($document, $analysis));

        return [$knowledgePath, ...array_values($paths)];
    }

    /**
     * @param array<string, mixed> $document
     * @param list<FileRecord> $records
     * @return KnowledgeAnalysis
     */
    private function analysis(array $document, array $records): array
    {
        /** @var KnowledgeDocument $document */
        $types = [];
        $relationships = [];
        $languages = [];
        $degrees = [];

        foreach ($document['nodes'] as $node) {
            $types[$node['type']] = ($types[$node['type']] ?? 0) + 1;
        }

        foreach ($document['edges'] as $edge) {
            $relationships[$edge['relation']] = ($relationships[$edge['relation']] ?? 0) + 1;
            $degrees[$edge['source']] = ($degrees[$edge['source']] ?? 0) + 1;
            $degrees[$edge['target']] = ($degrees[$edge['target']] ?? 0) + 1;
        }

        foreach ($records as $record) {
            $languages[$record['language']] = ($languages[$record['language']] ?? 0) + 1;
        }

        ksort($types);
        ksort($relationships);
        ksort($languages);
        $graphAnalysis = new KnowledgeGraphAnalyzer()->analyze($document);

        return [
            'schema' => 'phpforge.knowledge-analysis',
            'schema_version' => 2,
            'fingerprint' => $document['fingerprint'],
            'node_count' => count($document['nodes']),
            'edge_count' => count($document['edges']),
            'file_count' => count($records),
            'node_types' => $types,
            'relationships' => $relationships,
            'languages' => $languages,
            'central_nodes' => $this->centralNodes($document, $degrees),
            ...$graphAnalysis,
        ];
    }

    /** @param array<string, string> $paths */
    private function assertWritableTargets(array $paths): void
    {
        foreach ($paths as $type => $path) {
            if (!is_file($path)) {
                continue;
            }

            $contents = file_get_contents($path);
            $owned = match ($type) {
                'manifest' => $this->hasSchema($contents, 'phpforge.knowledge-manifest'),
                'analysis' => $this->hasSchema($contents, 'phpforge.knowledge-analysis'),
                'report' => is_string($contents) && str_starts_with($contents, self::REPORT_MARKER),
                'html' => is_string($contents) && str_contains($contents, self::HTML_MARKER),
                default => false,
            };

            if (!$owned) {
                throw new \RuntimeException(sprintf('Refusing to overwrite non-PHPForge artifact: %s', $path));
            }
        }
    }

    /**
     * @param array<string, mixed> $document
     * @param array<string, int> $degrees
     * @return list<array{id:string,type:string,name:string,file:string,degree:int}>
     */
    private function centralNodes(array $document, array $degrees): array
    {
        /** @var KnowledgeDocument $document */
        $nodes = [];

        foreach ($document['nodes'] as $node) {
            if (!$node['defined']) {
                continue;
            }

            $nodes[] = [
                'id' => $node['id'],
                'type' => $node['type'],
                'name' => $node['name'],
                'file' => $node['file'],
                'degree' => $degrees[$node['id']] ?? 0,
            ];
        }

        usort($nodes, static fn(array $left, array $right): int => $right['degree'] <=> $left['degree'] ?: $left['id'] <=> $right['id']);

        return array_slice($nodes, 0, 20);
    }

    private function hasSchema(string|false $contents, string $schema): bool
    {
        if (!is_string($contents)) {
            return false;
        }

        try {
            $decoded = json_decode($contents, true, 32, JSON_THROW_ON_ERROR);
        } catch (\JsonException) {
            return false;
        }

        return is_array($decoded) && ($decoded['schema'] ?? null) === $schema;
    }

    /**
     * @param array<string, mixed> $document
     * @param KnowledgeAnalysis $analysis
     */
    private function html(array $document, array $analysis): string
    {
        /** @var KnowledgeDocument $document */
        $godIds = array_fill_keys(array_column($analysis['god_nodes'], 'id'), true);
        $graph = [
            'fingerprint' => $document['fingerprint'],
            'communities' => array_map(static fn(array $community): array => [
                'id' => $community['id'],
                'label' => $community['label'],
                'cohesion' => $community['cohesion'],
            ], $analysis['communities']),
            'nodes' => array_map(static fn(array $node): array => [
                'id' => $node['id'],
                'type' => $node['type'],
                'name' => $node['name'],
                'file' => $node['file'],
                'line' => $node['line'],
                'community' => $analysis['node_communities'][$node['id']] ?? null,
                'god' => isset($godIds[$node['id']]),
            ], $document['nodes']),
            'edges' => array_map(static fn(array $edge): array => [
                'source' => $edge['source'],
                'target' => $edge['target'],
            ], $document['edges']),
        ];
        $json = json_encode($graph, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);

        return str_replace('__PHPFORGE_GRAPH__', $json, <<<'HTML_WRAP'
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <meta name="generator" content="PHPForge knowledgebase">
          <title>PHPForge Knowledge Graph</title>
          <style>
            :root{color-scheme:dark;font:14px ui-monospace,SFMono-Regular,Consolas,monospace;background:#10151d;color:#dce7f5}*{box-sizing:border-box}body{margin:0;display:grid;grid-template-columns:minmax(0,1fr) 360px;height:100vh}main{position:relative;overflow:hidden}canvas{width:100%;height:100%;display:block}.panel{border-left:1px solid #344154;background:#151c26;padding:16px;overflow:auto}h1{font-size:17px;margin:0 0 12px}input,select{width:100%;margin:0 0 10px;padding:9px;border:1px solid #46566d;border-radius:5px;background:#0e141c;color:#fff}.muted{color:#91a1b7;font-size:12px}.item{padding:8px 0;border-bottom:1px solid #293546;cursor:pointer}.item:hover{color:#65d4ff}.badge{display:inline-block;padding:2px 5px;border-radius:4px;background:#253246;color:#bcd0e9;font-size:11px}.god{color:#f8df6b}#details{white-space:pre-wrap;word-break:break-word;margin-top:14px}@media(max-width:800px){body{grid-template-columns:1fr;grid-template-rows:55vh 45vh}.panel{border-left:0;border-top:1px solid #344154}}
          </style>
        </head>
        <body>
          <main><canvas id="graph"></canvas></main>
          <aside class="panel">
            <h1>PHPForge Knowledge Graph</h1>
            <p class="muted" id="stats"></p>
            <input id="search" type="search" placeholder="Search symbol or file">
            <select id="type"><option value="">All node types</option></select>
            <select id="community"><option value="">All communities</option></select>
            <div id="results"></div><pre id="details"></pre>
          </aside>
          <script>
            const data=__PHPFORGE_GRAPH__,canvas=document.querySelector('#graph'),ctx=canvas.getContext('2d'),search=document.querySelector('#search'),type=document.querySelector('#type'),community=document.querySelector('#community'),results=document.querySelector('#results'),details=document.querySelector('#details');
            const palette=['#65d4ff','#f5a65b','#9be564','#d693ff','#ff6b91','#f8df6b','#7adbb8','#75a7ff','#ff9f80','#b7df70'],types=[...new Set(data.nodes.map(n=>n.type))].sort(),colors=new Map(data.communities.map((c,i)=>[c.id,palette[i%palette.length]])),labels=new Map(data.communities.map(c=>[c.id,c.label]));
            function addOption(select,value,label){const option=document.createElement('option');option.value=String(value);option.textContent=label;select.append(option)}types.forEach(t=>addOption(type,t,t));data.communities.forEach(c=>addOption(community,c.id,`${c.label} (${Math.round(c.cohesion*100)}%)`));document.querySelector('#stats').textContent=`${data.nodes.length} nodes · ${data.edges.length} edges · ${data.communities.length} communities · ${data.fingerprint.slice(0,12)}`;
            function resize(){const d=devicePixelRatio||1;canvas.width=canvas.clientWidth*d;canvas.height=canvas.clientHeight*d;ctx.setTransform(d,0,0,d,0,0);draw()}function position(n,i){const w=canvas.clientWidth,h=canvas.clientHeight,a=i*2.399963,r=Math.sqrt((i+1)/data.nodes.length)*Math.min(w,h)*.46;return{x:w/2+Math.cos(a)*r,y:h/2+Math.sin(a)*r,n}}
            let placed=[];function draw(selected=''){placed=data.nodes.map(position);const locations=new Map(placed.map(p=>[p.n.id,p]));ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.strokeStyle='#253246';ctx.globalAlpha=.24;data.edges.forEach(e=>{const a=locations.get(e.source),b=locations.get(e.target);if(a&&b){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}});ctx.globalAlpha=1;placed.forEach(p=>{ctx.fillStyle=p.n.id===selected?'#fff':(colors.get(p.n.community)||'#657184');ctx.beginPath();ctx.arc(p.x,p.y,p.n.id===selected?6:(p.n.god?4:2),0,Math.PI*2);ctx.fill()})}
            function show(n){details.textContent=`${n.god?'★ God node\n':''}${n.name}\n${n.type}\nCommunity: ${labels.get(n.community)||'(external)'}\n${n.file||'(external)'}:${n.line}\n${n.id}`;draw(n.id)}function filter(){const q=search.value.toLowerCase(),t=type.value,c=community.value;const found=data.nodes.filter(n=>(!t||n.type===t)&&(!c||String(n.community)===c)&&(!q||`${n.name} ${n.file} ${n.id}`.toLowerCase().includes(q))).slice(0,50);results.replaceChildren(...found.map(n=>{const d=document.createElement('div');d.className=`item${n.god?' god':''}`;const badge=document.createElement('span');badge.className='badge';badge.textContent=n.type;d.append(badge,document.createTextNode(` ${n.god?'★ ':''}${n.name}`));d.onclick=()=>show(n);return d}))}search.oninput=filter;type.onchange=filter;community.onchange=filter;canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const p=placed.find(p=>Math.hypot(p.x-x,p.y-y)<7);if(p)show(p.n)};addEventListener('resize',resize);resize();filter();
          </script>
        </body>
        </html>
        HTML_WRAP);
    }

    /**
     * @param array<string, mixed> $document
     * @param list<FileRecord> $records
     * @return array<string, mixed>
     */
    private function manifest(array $document, array $records): array
    {
        /** @var KnowledgeDocument $document */
        return [
            'schema' => 'phpforge.knowledge-manifest',
            'schema_version' => 1,
            'fingerprint' => $document['fingerprint'],
            'source_graph' => $document['source_graph'],
            'extractors' => $document['extractors'],
            'files' => $records,
        ];
    }

    private function markdown(string $value): string
    {
        return str_replace(["\r", "\n", '|'], ['', ' ', '\\|'], $value);
    }

    /** @return array{manifest:string,analysis:string,report:string,html:string} */
    private function paths(string $knowledgePath): array
    {
        $directory = dirname($knowledgePath);

        return [
            'manifest' => $directory . DIRECTORY_SEPARATOR . 'manifest.json',
            'analysis' => $directory . DIRECTORY_SEPARATOR . 'analysis.json',
            'report' => $directory . DIRECTORY_SEPARATOR . 'GRAPH_REPORT.md',
            'html' => $directory . DIRECTORY_SEPARATOR . 'graph.html',
        ];
    }

    /**
     * @param array<string, mixed> $document
     * @param KnowledgeAnalysis $analysis
     */
    private function report(array $document, array $analysis): string
    {
        /** @var KnowledgeDocument $document */
        $lines = [
            self::REPORT_MARKER,
            '# PHPForge Knowledge Report',
            '',
            sprintf('- Fingerprint: `%s`', $document['fingerprint']),
            sprintf('- Files: %d', $analysis['file_count']),
            sprintf('- Nodes: %d', $analysis['node_count']),
            sprintf('- Edges: %d', $analysis['edge_count']),
            '',
            '## File coverage',
            '',
            '| Category | Files |',
            '| --- | ---: |',
        ];

        foreach ($document['files'] as $category => $files) {
            $lines[] = sprintf('| %s | %d |', str_replace('_', '-', $category), count($files));
        }

        $lines = [...$lines, '', '## Languages', '', '| Language | Files |', '| --- | ---: |'];

        foreach ($analysis['languages'] as $language => $count) {
            $lines[] = sprintf('| %s | %d |', $this->markdown($language), $count);
        }

        $lines = [...$lines, '', '## Relationships', '', '| Relation | Edges |', '| --- | ---: |'];

        foreach ($analysis['relationships'] as $relation => $count) {
            $lines[] = sprintf('| %s | %d |', $this->markdown($relation), $count);
        }

        $health = $analysis['graph_health'];
        $communityHubs = array_values(array_filter(
            $analysis['communities'],
            static fn(array $community): bool => $community['file_count'] > 1
                || ($community['node_count'] >= 5 && $community['external_edges'] > 0),
        ));
        $thinCommunities = count($analysis['communities']) - count($communityHubs);
        $lines = [
            ...$lines,
            '',
            '## Graph health',
            '',
            sprintf('- Connected components: %d', $health['connected_components']),
            sprintf('- Isolated nodes: %d', $health['isolated_nodes']),
            sprintf('- Self loops: %d', $health['self_loops']),
            sprintf('- Dangling edges: %d', $health['dangling_edges']),
            sprintf('- Density: %.8f', $health['density']),
            '',
            sprintf('## Community Hubs (%d)', count($communityHubs)),
            '',
            sprintf('%d thin standalone communities are retained in `analysis.json` and the HTML explorer but omitted here.', $thinCommunities),
            '',
            '| ID | Community | Nodes | Files | Cohesion | Internal / external edges |',
            '| ---: | --- | ---: | ---: | ---: | ---: |',
        ];

        foreach ($communityHubs as $community) {
            $lines[] = sprintf(
                '| %d | %s | %d | %d | %.3f | %d / %d |',
                $community['id'],
                $this->markdown($community['label']),
                $community['node_count'],
                $community['file_count'],
                $community['cohesion'],
                $community['internal_edges'],
                $community['external_edges'],
            );
        }

        $lines = [...$lines, '', '## God Nodes', '', '| Degree | Communities | Type | Name | File |', '| ---: | ---: | --- | --- | --- |'];

        foreach ($analysis['god_nodes'] as $node) {
            $lines[] = sprintf(
                '| %d | %d | %s | `%s` | %s |',
                $node['degree'],
                $node['communities_reached'],
                $this->markdown($node['type']),
                str_replace('`', '\\`', $this->markdown($node['name'])),
                $this->markdown($node['file']),
            );
        }

        $lines = [...$lines, '', '## Surprising Connections', ''];

        if ($analysis['surprising_connections'] === []) {
            $lines[] = 'No extracted cross-community connections were found.';
        } else {
            foreach ($analysis['surprising_connections'] as $connection) {
                $lines[] = sprintf(
                    '- `%s` → `%s` (%s, %s at %s:%d) — %s',
                    str_replace('`', '\\`', $this->markdown($connection['source_name'])),
                    str_replace('`', '\\`', $this->markdown($connection['target_name'])),
                    $this->markdown($connection['relation']),
                    strtoupper($this->markdown($connection['certainty'])),
                    $this->markdown($connection['file']),
                    $connection['line'],
                    $this->markdown($connection['why']),
                );
            }
        }

        $lines = [...$lines, '', '## Suggested Questions', ''];

        foreach ($analysis['suggested_questions'] as $question) {
            $lines[] = sprintf('- %s — %s', $this->markdown($question['question']), $this->markdown($question['why']));
        }

        $lines[] = '';
        $lines[] = 'Communities, god nodes, bridges and questions are deterministic analysis of extracted relationships. Optional AI explanations remain inferred and are not written into this report.';
        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }

    private function write(string $path, string $contents): void
    {
        $temporary = tempnam(dirname($path), '.phpforge-artifact-');

        if (!is_string($temporary)) {
            throw new \RuntimeException(sprintf('Could not create a temporary artifact in: %s', dirname($path)));
        }

        try {
            if (file_put_contents($temporary, $contents, LOCK_EX) === false || !rename($temporary, $path)) {
                throw new \RuntimeException(sprintf('Could not publish PHPForge artifact: %s', $path));
            }
        } finally {
            if (is_file($temporary)) {
                unlink($temporary);
            }
        }
    }

    /** @param array<string, mixed> $document */
    private function writeJson(string $path, array $document): void
    {
        $this->write($path, json_encode($document, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . PHP_EOL);
    }
}
