<?php

declare(strict_types=1);

return [
    'mysql' => [
        'label' => 'MySQL',
        'external' => true,
        'extensions' => ['pdo_mysql'],
        'host' => '127.0.0.1',
        'port' => 3306,
        'environment' => ['IC_MYSQL_DSN', 'IC_MYSQL_PRIMARY_DSN', 'IC_MYSQL_REPLICA_DSN', 'IC_MYSQL_USER', 'IC_MYSQL_PASSWORD'],
        'endpoint_template' => 'mysql:host={host};port={port};dbname={database};charset=utf8mb4',
        'probe' => 'mysql',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'mysql', 'replica' => 'mysql-replica'],
    ],
    'mariadb' => [
        'label' => 'MariaDB',
        'external' => true,
        'extensions' => ['pdo_mysql'],
        'host' => '127.0.0.1',
        'port' => 3308,
        'environment' => ['IC_MARIADB_DSN', 'IC_MARIADB_PRIMARY_DSN', 'IC_MARIADB_REPLICA_DSN', 'IC_MARIADB_USER', 'IC_MARIADB_PASSWORD'],
        'endpoint_template' => 'mysql:host={host};port={port};dbname={database};charset=utf8mb4',
        'probe' => 'mariadb',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'mariadb', 'replica' => 'mariadb-replica'],
    ],
    'postgres' => [
        'label' => 'PostgreSQL',
        'external' => true,
        'extensions' => ['pdo_pgsql'],
        'host' => '127.0.0.1',
        'port' => 5432,
        'environment' => ['IC_POSTGRES_DSN', 'IC_POSTGRES_PRIMARY_DSN', 'IC_POSTGRES_REPLICA_DSN', 'IC_POSTGRES_USER', 'IC_POSTGRES_PASSWORD'],
        'endpoint_template' => 'pgsql:host={host};port={port};dbname={database}',
        'probe' => 'postgres',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'postgres', 'replica' => 'postgres-replica'],
    ],
    'mssql' => [
        'label' => 'Microsoft SQL Server',
        'external' => true,
        'extensions' => ['pdo_sqlsrv'],
        'host' => '127.0.0.1',
        'port' => 1433,
        'environment' => ['IC_MSSQL_DSN', 'IC_MSSQL_PRIMARY_DSN', 'IC_MSSQL_REPLICA_DSN', 'IC_MSSQL_USER', 'IC_MSSQL_PASSWORD'],
        'endpoint_template' => 'sqlsrv:Server={host},{port};TrustServerCertificate=1',
        'probe' => 'mssql',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'mssql', 'availability-group' => 'mssql-availability-group'],
    ],
    'sqlite' => [
        'label' => 'SQLite',
        'external' => false,
        'extensions' => ['pdo_sqlite'],
        'host' => null,
        'port' => null,
        'environment' => ['IC_SQLITE_MEMORY_DSN', 'IC_SQLITE_FILE_DSN'],
        'endpoint_template' => 'sqlite:{path}',
        'probe' => 'sqlite',
        'retry_attempts' => 1,
        'topologies' => ['standalone' => null],
    ],
    'mongodb' => [
        'label' => 'MongoDB',
        'external' => true,
        'extensions' => ['mongodb'],
        'host' => '127.0.0.1',
        'port' => 27017,
        'environment' => ['IC_MONGODB_DSN', 'IC_MONGODB_REPLICA_SET'],
        'endpoint_template' => 'mongodb://{username}:{password}@{host}:{port}/{database}?authSource=admin',
        'probe' => 'mongodb',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'mongodb', 'replica-set' => 'mongodb-replica'],
    ],
    'redis' => [
        'label' => 'Redis',
        'external' => true,
        'extensions' => ['redis'],
        'host' => '127.0.0.1',
        'port' => 6379,
        'environment' => ['IC_REDIS_HOST', 'IC_REDIS_PORT', 'IC_REDIS_REPLICA_HOST', 'IC_REDIS_REPLICA_PORT', 'IC_REDIS_PASSWORD'],
        'endpoint_template' => 'redis://:{password}@{host}:{port}',
        'probe' => 'redis',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'redis', 'replica' => 'redis-replica'],
    ],
    'valkey' => [
        'label' => 'Valkey',
        'external' => true,
        'extensions' => ['redis'],
        'host' => '127.0.0.1',
        'port' => 6380,
        'environment' => ['IC_VALKEY_HOST', 'IC_VALKEY_PORT', 'IC_VALKEY_REPLICA_HOST', 'IC_VALKEY_REPLICA_PORT', 'IC_VALKEY_PASSWORD'],
        'endpoint_template' => 'redis://:{password}@{host}:{port}',
        'probe' => 'valkey',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'valkey', 'replica' => 'valkey-replica'],
    ],
    'memcached' => [
        'label' => 'Memcached',
        'external' => true,
        'extensions' => ['memcached'],
        'host' => '127.0.0.1',
        'port' => 11211,
        'environment' => ['IC_MEMCACHED_HOST', 'IC_MEMCACHED_PORT'],
        'endpoint_template' => '{host}:{port}',
        'probe' => 'memcached',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'memcached'],
    ],
    'rabbitmq' => [
        'label' => 'RabbitMQ',
        'external' => true,
        'extensions' => [],
        'host' => '127.0.0.1',
        'port' => 5672,
        'environment' => ['IC_RABBITMQ_HOST', 'IC_RABBITMQ_PORT', 'IC_RABBITMQ_DSN', 'IC_RABBITMQ_MANAGEMENT_URL', 'IC_RABBITMQ_CLUSTER_NODES'],
        'endpoint_template' => 'amqp://{username}:{password}@{host}:{port}',
        'probe' => 'rabbitmq',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'rabbitmq', 'cluster' => 'rabbitmq-cluster'],
    ],
    'nats' => [
        'label' => 'NATS with JetStream',
        'external' => true,
        'extensions' => [],
        'host' => '127.0.0.1',
        'port' => 4222,
        'environment' => ['IC_NATS_URL', 'IC_NATS_MONITOR_URL', 'IC_NATS_CLUSTER_URLS'],
        'endpoint_template' => 'nats://{host}:{port}',
        'probe' => 'nats',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'nats', 'cluster' => 'nats-cluster'],
    ],
    'mailpit' => [
        'label' => 'Mailpit',
        'external' => true,
        'extensions' => [],
        'host' => '127.0.0.1',
        'port' => 1025,
        'environment' => ['IC_SMTP_HOST', 'IC_SMTP_PORT', 'IC_SMTP_DSN', 'IC_MAILPIT_URL', 'IC_MAILPIT_API_URL'],
        'endpoint_template' => 'smtp://{host}:{port}',
        'probe' => 'mailpit',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'mailpit'],
    ],
    'elasticsearch' => [
        'label' => 'Elasticsearch',
        'external' => true,
        'extensions' => [],
        'host' => '127.0.0.1',
        'port' => 9200,
        'environment' => ['IC_ELASTICSEARCH_HOST', 'IC_ELASTICSEARCH_PORT', 'IC_ELASTICSEARCH_URL', 'IC_ELASTICSEARCH_CLUSTER_URLS'],
        'endpoint_template' => 'http://{host}:{port}',
        'probe' => 'elasticsearch',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'elasticsearch', 'cluster' => 'elasticsearch-cluster'],
    ],
    'scylladb' => [
        'label' => 'ScyllaDB Alternator',
        'external' => true,
        'extensions' => [],
        'host' => '127.0.0.1',
        'port' => 8000,
        'environment' => ['IC_SCYLLADB_HOST', 'IC_SCYLLADB_PORT', 'IC_SCYLLADB_ENDPOINT', 'IC_SCYLLADB_ADMIN_URL', 'IC_SCYLLADB_CLUSTER_ENDPOINTS', 'IC_SCYLLADB_REGION', 'IC_SCYLLADB_ACCESS_KEY_ID', 'IC_SCYLLADB_SECRET_ACCESS_KEY'],
        'endpoint_template' => 'http://{host}:{port}',
        'probe' => 'scylladb',
        'retry_attempts' => 60,
        'topologies' => ['standalone' => 'scylladb', 'cluster' => 'scylladb-cluster'],
    ],
];
